package com.receiptofi.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

/**
 * User: hitender
 * Date: 4/13/14 5:11 PM
 */
@Document(collection = "GENERATE_USER_IDS")
public final class GenerateUserIds {

    @Id
    private final String className;

    @Field("RID")
    private long autoGeneratedReceiptUserId = 10_000_000_001L;

    public GenerateUserIds(String className) {
        this.className = className;
    }

    public static GenerateUserIds newInstance() {
        return new GenerateUserIds(GenerateUserIds.class.getName());
    }

    public long getAutoGeneratedReceiptUserId() {
        return autoGeneratedReceiptUserId;
    }
}
