package com.receiptofi.repository;

import com.receiptofi.domain.GenerateUserIds;

/**
 * User: hitender
 * Date: 4/13/14 5:18 PM
 */
public interface GenerateUserIdManager extends RepositoryManager<GenerateUserIds> {

    String getNextAutoGeneratedUserId();
}
