/**
 *
 */
package com.receiptofi.repository;

import com.receiptofi.domain.BizNameEntity;
import com.receiptofi.domain.BizStoreEntity;
import com.receiptofi.domain.ReceiptEntity;
import com.receiptofi.domain.value.ReceiptGrouped;
import com.receiptofi.domain.value.ReceiptGroupedByBizLocation;

import java.util.Iterator;
import java.util.List;

import org.joda.time.DateTime;

/**
 * @author hitender
 * @since Dec 26, 2012 3:09:48 PM
 *
 */
public interface ReceiptManager extends RepositoryManager<ReceiptEntity> {

    /**
     * @param receiptId
     * @param userProfileId
     * @return
     */
    ReceiptEntity findReceipt(String receiptId, String userProfileId);

    /**
     * Get receipt for specific user.
     *
     * @param receiptId
     * @param userProfileId
     * @return
     */
    ReceiptEntity findOne(String receiptId, String userProfileId);

    /**
     * Find all receipts with BizName for the user
     * @param bizNameEntity
     * @param userProfileId
     * @return
     */
    List<ReceiptEntity> findReceipt(BizNameEntity bizNameEntity, String userProfileId);

    /**
     * Gets all the user receipts. Refrain from using open ended query.
     *
     * @param userProfileId
     * @return
     */
	List<ReceiptEntity> getAllReceipts(String userProfileId);

    /**
     * Get receipts only the selected year
     *
     * @param userProfileId
     * @param startOfTheYear
     * @return
     */
	List<ReceiptEntity> getAllReceiptsForTheYear(String userProfileId, DateTime startOfTheYear);

    /**
     * Gets user receipts for current month
     *
     * @param userProfileId
     * @return
     */
    List<ReceiptEntity> getAllReceiptsForThisMonth(String userProfileId, DateTime monthYear);

    /**
     * Get receipts associated with year, month, day
     *
     * @param year
     * @param month
     * @param day
     * @param userProfileId
     * @return
     */
    List<ReceiptEntity> findThisDayReceipts(int year, int month, int day, String userProfileId);

    /**
     * Receipt grouped by day
     *
     * @param userProfileId
     * @return
     */
    Iterator<ReceiptGrouped> getAllObjectsGroupedByDate(String userProfileId);

    /**
     * Receipt grouped by month for last 13 months
     *
     * @param userProfileId
     * @return
     */
    Iterator<ReceiptGrouped> getAllObjectsGroupedByMonth(String userProfileId);

    /**
     * Group receipts by location and sum up the total expense on that particular business location
     *
     * @param userProfileId
     * @return
     */
    Iterator<ReceiptGroupedByBizLocation> getAllReceiptGroupedByBizLocation(String userProfileId);

    @Deprecated
    List<String> findTitles(String title);

    ReceiptEntity findWithReceiptOCR(String receiptOCRId);

    void deleteSoft(ReceiptEntity object);

    /**
     * Count includes all active and inactive receipts
     *
     * @param bizStoreEntity
     * @return
     */
    long countAllReceiptForAStore(BizStoreEntity bizStoreEntity);

    /**
     * Count includes all active and inactive receipts
     *
     * @param bizNameEntity
     * @return
     */
    long countAllReceiptForABizName(BizNameEntity bizNameEntity);

    /**
     * Check if not deleted receipt exists
     *
     * @param checksum
     * @return
     */
    boolean notDeletedChecksumDuplicate(String checksum, String id);

    /**
     * Return existing active receipt. This method will be helpful when we plan to notify technician about the duplicate
     * receipt. Example when similar receipt exists in re-check condition.
     *
     * @param checksum
     * @return
     */
    ReceiptEntity findNotDeletedChecksumDuplicate(String checksum, String id);

    /**
     * Find if receipt with similar checksum exists
     *
     * @param checksum
     * @return
     */
    boolean hasRecordWithSimilarChecksum(String checksum);

    /**
     * Removes reference to expensofi file name in file system. This is expense excel file generated by user.
     *
     * @param filename
     */
    void removeExpensofiFilenameReference(String filename);
}
